version: '3.9'
services:
  db:
    image: postgres:15-alpine
    container_name: quotation_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quote_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/quote_db?schema=public
      - PORT=3000
      - LOG_LEVEL=info
      - DEFAULT_CURRENCY=USD
      - CACHE_TTL_MS=30000
    ports:
      - "3000:3000"

volumes:
  db_data:
    driver: local


